version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    # Security-critical linters
    - gosec
    - errorlint
    - noctx
    - bodyclose
    - sqlclosecheck

    # Code quality
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Error handling
    - errcheck

    # Best practices
    - gocritic
    - unconvert
    - dupl
    - goconst
    - misspell
    - nakedret
    - prealloc
    - predeclared
    - copyloopvar

  settings:
    gosec:
      excludes:
        - G104  # We'll use errcheck instead

    govet:
      disable:
        - fieldalignment  # Performance optimization, not critical for correctness

    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (*database/sql.Rows).Close
        - (*github.com/jmoiron/sqlx.Rows).Close
        - (*database/sql.Tx).Rollback
        - (*github.com/jmoiron/sqlx.Tx).Rollback

    gocritic:
      enabled-checks:
        - deferInLoop
        - emptyFallthrough
        - evalOrder
        - nilValReturn
        - rangeExprCopy
        - rangeValCopy
        - sqlQuery
        - truncateCmp
        - weakCond

    dupl:
      threshold: 300

    goconst:
      min-len: 3
      min-occurrences: 3

    misspell:
      locale: US

  exclusions:
    rules:
      # Test files can have duplication and unchecked errors
      - path: '(.+)_test\.go'
        linters:
          - goconst
          - dupl
          - govet
          - errcheck
          - gosec

      # Testing package has intentional patterns
      - path: 'testing/'
        linters:
          - errcheck
          - goconst
          - dupl
          - gosec

formatters:
  enable:
    - gofmt
    - goimports
